esphome:
  name: media-control
  friendly_name: Media Controller
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

captive_portal:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  # VOLUME KNOB BUTTON ----------------------
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Volume Switch Button"
    on_press:
      - homeassistant.service:
          service: media_player.media_play_pause
          data:
              entity_id: media_player.TV_MEDIA_ENTITY_ID
      - logger.log: "single click - play/pause"
  # KEY BUTTONS ----------------------

  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 1"
    on_press:
      - homeassistant.service:
          service: media_player.toggle
          data:
              entity_id: media_player.TV_MEDIA_ENTITY_ID
      - logger.log: "Button 1 - toggle"
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 1"
    on_multi_click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: script.watch_movie_volume # defined as a script in Home Assistant
        - logger.log: "Button 2 - Watch movie volume"
    - timing:
      - ON for at most .49s
      - OFF for at least 0.25s
      then:
        - homeassistant.service:
            service: script.watch_news_volume # defined as a script in Home Assistant
        - logger.log: "Button 2 - Watch news volume"
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button 3"
    on_press:
      - homeassistant.service:
          service: script.kill_lights # defined as a script in Home Assistant
      - logger.log: "Button 3 - Watch TV lighting"

    
sensor:
  - platform: rotary_encoder
    id: knob_family
    name: "${friendly_name} Rotary Encoder"
    pin_b: D7
    pin_a: D5
    min_value: -3
    max_value: 3
    on_value_range:
      - above: 2
        then:
          - script.execute: volume_up
      - below: -2
        then:
          - script.execute: volume_down
              
script:
  - id: volume_up
    then:
      - homeassistant.service:
          service: media_player.volume_up
          data:
            entity_id: media_player.denon_avr
      - logger.log: "vol up trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_family
          value: 0
  - id: volume_down
    then:
      - homeassistant.service:
          service: media_player.volume_down
          data:
            entity_id: media_player.denon_avr
      - logger.log: "vol down trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_family
          value: 0      

