esphome:
  name: volume-control
  friendly_name: Volume Controller
  platform: ESP8266
  board: d1_mini

# Enable Home Assistant API
api:

ota:

captive_portal:

# Enable logging
logger: 
    
binary_sensor:
  - platform: gpio
    id: button_family
    pin:
      number: D2 
      mode: INPUT_PULLUP
      inverted: True
    on_multi_click:
    - timing:
      # double click
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - homeassistant.service:
            service: media_player.media_next_track
            data:
              entity_id: media_player.spotify
        - logger.log: "double click - next track"
    - timing:
      # single click
      - ON for at most .49s
      - OFF for at least 0.25s
      then:
        - homeassistant.service:
            service: media_player.media_play_pause
            data:
              entity_id: media_player.YOUR_TV_MEDIA_PLAYER
        - logger.log: "single click - play/pause"

sensor:
  - platform: rotary_encoder
    id: knob_family
    pin_a: D4
    pin_b: D3
    min_value: -2
    max_value: 2
    resolution: 1
    filters:
      - or:
        - debounce: 0.1s
        - delta: 10
    on_value_range:
      - above: 1
        then:
          - script.execute: volume_up
      - below: -1
        then:
          - script.execute: volume_down
script:
  - id: volume_up
    then:
      - homeassistant.service:
          service: media_player.volume_up
          data:
            entity_id: media_player.YOUR_AUDIO_OUTPUT_PLAYER_ID
      - logger.log: "vol up trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_family
          value: 0
  - id: volume_down
    then:
      - homeassistant.service:
          service: media_player.volume_down
          data:
            entity_id: media_player.YOUR_AUDIO_OUTPUT_PLAYER_ID
      - logger.log: "vol down trigger"
      - sensor.rotary_encoder.set_value:
          id: knob_family
          value: 0
  - id: start_playlist_shuffle
    then:
      - homeassistant.service:
          service: media_player.play_media
          data:
            entity_id: media_player.spotify
            media_content_id: spotify:playlist:YOUR_PLAYLIST_ID
            media_content_type: playlist
      - homeassistant.service:
          service: media_player.shuffle_set
          data:
            entity_id: media_player.spotify
            shuffle: "true"
      - homeassistant.service:
          service: media_player.media_next_track
          data:
            entity_id: media_player.spotify

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

